# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-12 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField(verbose_name='بید')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'ordering': ('-bid',),
                'verbose_name_plural': 'بیدها',
                'verbose_name': 'بید',
            },
        ),
        migrations.CreateModel(
            name='BiddingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(blank=True, max_length=900, null=True, verbose_name='لاگ بید')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'ordering': ('-creation_time',),
                'verbose_name_plural': 'لاگ\u200cهای بید',
                'verbose_name': 'لاگ بید',
            },
        ),
        migrations.CreateModel(
            name='Pelak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='شماره پلاک')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'ordering': ('-creation_time',),
                'verbose_name_plural': 'پلاک\u200cها',
                'verbose_name': 'پلاک',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='یوزرنیم تلگرام')),
                ('tg_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='شناسه کاربری تلگرام')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره تلفن')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخرین حضور')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'افراد',
                'verbose_name': 'فرد',
            },
        ),
        migrations.AddField(
            model_name='pelak',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pelaks', to='tgbot.Person', verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='biddinglog',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tgbot.Person', verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='bid',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tgbot.Person', verbose_name='کاربر'),
        ),
    ]
